/**
 * Schedule Page Component
 * 
 * Displays the course schedule generated by Classasaurus plugin
 */

import React, { useEffect, useMemo, useState } from 'react';
import Layout from '@theme/Layout';
import Link from '@docusaurus/Link';
import useBaseUrl from '@docusaurus/useBaseUrl';
import { parseISO, format, startOfWeek, endOfWeek, getDay, addDays, isWithinInterval, isSameWeek } from 'date-fns';
import type { CourseSchedule, ScheduleEntry, Lab, Assignment, CourseSection, LabSection, ScheduleNote } from '@site/plugins/classasaurus/types';
import { Alert, Box } from '@chakra-ui/react';
import { LuConstruction } from 'react-icons/lu';

// Type alias for date strings (ISO format)
type DateString = string;

// Component props - scheduleData comes from the plugin's modules
export interface Props {
  readonly scheduleData: CourseSchedule;
}

// Map day names to day numbers (0 = Sunday, 6 = Saturday)
const DAY_NAME_TO_NUMBER: { [key: string]: number } = {
  'Sunday': 0,
  'Monday': 1,
  'Tuesday': 2,
  'Wednesday': 3,
  'Thursday': 4,
  'Friday': 5,
  'Saturday': 6
};

// Helper to get day of week name from a date
function getDayOfWeekName(date: Date): string {
  const dayNumber = getDay(date);
  const dayNames = ['Sunday', 'Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday'];
  return dayNames[dayNumber];
}

// Helper to get alert colors based on status
function getAlertColors(status: 'info' | 'warning' | 'error' | 'success'): { bg: string; border: string } {
  const colors = {
    info: { bg: '#dbeafe', border: '#3b82f6' }, // blue-100 bg, blue-500 border
    warning: { bg: '#fef3c7', border: '#f59e0b' }, // amber-100 bg, amber-500 border
    error: { bg: '#fee2e2', border: '#ef4444' }, // red-100 bg, red-500 border
    success: { bg: '#d1fae5', border: '#10b981' }, // emerald-100 bg, emerald-500 border
  };
  return colors[status] || colors.info;
}

// Helper to get the date for a specific day of week in a given week
function getDateForDayInWeek(weekStartDate: Date, dayName: string): DateString {
  const targetDayNumber = DAY_NAME_TO_NUMBER[dayName];
  const weekStartDayNumber = getDay(weekStartDate);

  let daysToAdd = targetDayNumber - weekStartDayNumber;
  if (daysToAdd < 0) {
    daysToAdd += 7;
  }

  const targetDate = addDays(weekStartDate, daysToAdd);
  return format(targetDate, 'yyyy-MM-dd');
}

// Helper to generate week structure for the schedule
function generateWeekStructure(entries: ScheduleEntry[], meetingDays: string[]): Map<number, Map<string, DateString>> {
  if (entries.length === 0) return new Map();

  // Find the range of dates
  const dates = entries.map(e => parseISO(e.date)).sort((a, b) => a.getTime() - b.getTime());
  const firstDate = dates[0];
  const lastDate = dates[dates.length - 1];

  // Start from the beginning of the week containing the first date
  const weekStart = startOfWeek(firstDate, { weekStartsOn: 0 }); // Sunday

  const weeks = new Map<number, Map<string, DateString>>();
  let currentWeekStart = weekStart;
  let weekNumber = 1;

  // Generate weeks until we pass the last date
  while (currentWeekStart <= lastDate) {
    const weekDates = new Map<string, DateString>();

    // For each meeting day, calculate what date it would be in this week
    meetingDays.forEach(dayName => {
      const dateStr = getDateForDayInWeek(currentWeekStart, dayName);
      const date = parseISO(dateStr);

      // Only include if it's within the course date range
      if (date >= firstDate && date <= lastDate) {
        weekDates.set(dayName, dateStr);
      }
    });

    // Only add week if it has at least one meeting day
    if (weekDates.size > 0) {
      weeks.set(weekNumber, weekDates);
      weekNumber++;
    }

    currentWeekStart = addDays(currentWeekStart, 7);
  }

  return weeks;
}

interface ScheduleTableProps {
  entries: ScheduleEntry[];
  sectionName?: string;
  lectureDays: string[]; // Days this section has lectures
  labDays: string[]; // Days this section has labs
  assignments: Assignment[]; // Course assignments
  scheduleNotes?: ScheduleNote[]; // Schedule notes for banners
  lectureSectionId?: string; // Selected lecture section ID
  labSectionId?: string; // Selected lab section ID
  getAssignmentUrl?: (url: string | undefined) => string | undefined; // Function to format assignment URLs with base URL
}

function ScheduleTable({ entries, sectionName, lectureDays, labDays, assignments, scheduleNotes = [], lectureSectionId, labSectionId, getAssignmentUrl }: ScheduleTableProps) {
  // Collect days of week from assignments (release and due dates)
  const assignmentDays = useMemo(() => {
    const days = new Set<string>();
    assignments.forEach(a => {
      if (a.assignedDate) {
        const dayName = getDayOfWeekName(parseISO(a.assignedDate));
        days.add(dayName);
      }
      if (a.dueDate) {
        const dayName = getDayOfWeekName(parseISO(a.dueDate));
        days.add(dayName);
      }
    });
    return Array.from(days);
  }, [assignments]);

  // Combine all meeting days (lectures, labs, and assignment days)
  const allMeetingDays = Array.from(new Set([...lectureDays, ...labDays, ...assignmentDays]));

  // Create a map of date -> entries for quick lookup (allow multiple meetings per date)
  const entryMap = new Map<DateString, ScheduleEntry[]>();
  entries.forEach(entry => {
    const existing = entryMap.get(entry.date) || [];
    entryMap.set(entry.date, [...existing, entry]);
  });

  // Generate the week structure based on all meeting days
  const weekStructure = generateWeekStructure(entries, allMeetingDays);
  const weekNumbers = Array.from(weekStructure.keys()).sort((a, b) => a - b);

  // Create assignment map by week (find assignments released or due during this week)
  const assignmentsByWeek = new Map<number, Assignment[]>();
  weekNumbers.forEach(weekNum => {
    const weekDates = weekStructure.get(weekNum)!;
    const allDatesInWeek = Array.from(weekDates.values());

    if (allDatesInWeek.length > 0) {
      // Use the first date to establish the week interval
      const referenceDate = parseISO(allDatesInWeek[0]);
      const weekStart = startOfWeek(referenceDate, { weekStartsOn: 0 });
      const weekEnd = endOfWeek(referenceDate, { weekStartsOn: 0 });

      // Find assignments released or due during this week
      const weekAssignments = assignments.filter(a => {
        // Skip assignments without dates
        if (!a.assignedDate || !a.dueDate) return false;

        const assignedDate = parseISO(a.assignedDate);
        const dueDate = parseISO(a.dueDate);

        // Include if assigned or due during this week using isWithinInterval
        return isWithinInterval(assignedDate, { start: weekStart, end: weekEnd }) ||
          isWithinInterval(dueDate, { start: weekStart, end: weekEnd });
      });

      if (weekAssignments.length > 0) {
        assignmentsByWeek.set(weekNum, weekAssignments);
      }
    }
  });

  // Use the section's actual meeting days for columns (in proper order)
  const allDays = ['Sunday', 'Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday'];
  const daysOfWeek = allDays.filter(day => allMeetingDays.includes(day));

  // Helper function to get schedule notes for a specific week
  const getNotesForWeek = (weekNum: number): ScheduleNote[] => {
    if (!scheduleNotes || scheduleNotes.length === 0) return [];
    
    return scheduleNotes.filter(note => {
      // Check if note applies to this week
      if (!note.weeks.includes(weekNum)) return false;
      
      // Check if note applies to selected sections
      const appliesToLecture = !note.sections || note.sections.length === 0 || 
        (lectureSectionId && note.sections.includes(lectureSectionId));
      const appliesToLab = !note.labSections || note.labSections.length === 0 || 
        (labSectionId && note.labSections.includes(labSectionId));
      
      // Note applies if it matches lecture section OR lab section (or both/all)
      return appliesToLecture || appliesToLab;
    });
  };

  return (
    <div>
      {sectionName && <h2>{sectionName}</h2>}
      <div style={{ overflowX: 'auto', overflowY: 'visible' }}>
        <table style={{ width: '100%', borderCollapse: 'collapse', marginBottom: '2rem' }}>
          <thead style={{ position: 'sticky', top: 0, zIndex: 10 }}>
            <tr style={{ borderBottom: '2px solid var(--ifm-color-emphasis-300)' }}>
              <th style={{
                padding: '0.75rem',
                textAlign: 'left',
                width: '80px',
                backgroundColor: 'var(--ifm-background-color)',
                borderBottom: '2px solid var(--ifm-color-emphasis-300)'
              }}>
                Week
              </th>
              {daysOfWeek.map(day => (
                <th key={day} style={{
                  padding: '0.75rem',
                  textAlign: 'left',
                  backgroundColor: 'var(--ifm-background-color)',
                  borderBottom: '2px solid var(--ifm-color-emphasis-300)'
                }}>
                  {day.slice(0, 3)}
                </th>
              ))}
            </tr>
          </thead>
          <tbody>
            {weekNumbers.map((weekNum) => {
              const datesByDay = weekStructure.get(weekNum)!;
              const weekNotes = getNotesForWeek(weekNum);

              return (
                <React.Fragment key={weekNum}>
                  {/* Schedule note banner row */}
                  {weekNotes.length > 0 && weekNotes.map((note, noteIdx) => {
                    // Find which column the date falls into (if specified)
                    let dateColumnIndex = -1;
                    if (note.date) {
                      const noteDate = parseISO(note.date);
                      const noteDayOfWeek = getDayOfWeekName(noteDate);
                      dateColumnIndex = daysOfWeek.findIndex(day => day === noteDayOfWeek);
                    }
                    
                    // Calculate triangle position: account for Week column (index 0) + date column
                    // Total columns = 1 (Week) + daysOfWeek.length
                    const totalColumns = daysOfWeek.length + 1;
                    const triangleLeftPercent = dateColumnIndex >= 0 
                      ? ((dateColumnIndex + 1) / totalColumns) * 100 
                      : 50; // Center if no date specified
                    
                    const alertColors = getAlertColors(note.status || 'info');
                    const hasTriangle = dateColumnIndex >= 0;
                    
                    return (
                      <React.Fragment key={`note-${weekNum}-${noteIdx}`}>
                        <tr style={{ borderBottom: '1px solid var(--ifm-color-emphasis-200)' }}>
                          <td 
                            colSpan={daysOfWeek.length + 1} 
                            style={{ 
                              padding: 0,
                              position: 'relative'
                            }}
                          >
                            <div style={{ position: 'relative' }}>
                              <Alert.Root status={note.status || 'info'}>
                                <Alert.Indicator />
                                <Alert.Title>{note.message}</Alert.Title>
                              </Alert.Root>
                              {/* Speech bubble triangle - attached to alert, positioned relative to table cell */}
                              {hasTriangle && (
                                <div style={{
                                  position: 'absolute',
                                  bottom: '-12px',
                                  left: `${triangleLeftPercent}%`,
                                  transform: 'translateX(-50%)',
                                  width: 0,
                                  height: 0,
                                  // Outer triangle (border) - matches alert border
                                  borderLeft: '10px solid transparent',
                                  borderRight: '10px solid transparent',
                                  borderTop: `12px solid ${alertColors.border}`,
                                }}>
                                  {/* Inner triangle (background) to create border effect */}
                                  <div style={{
                                    position: 'absolute',
                                    top: '-12px',
                                    left: '-9px',
                                    width: 0,
                                    height: 0,
                                    borderLeft: '9px solid transparent',
                                    borderRight: '9px solid transparent',
                                    borderTop: `11px solid ${alertColors.bg}`,
                                  }} />
                                </div>
                              )}
                            </div>
                          </td>
                        </tr>
                      </React.Fragment>
                    );
                  })}
                  {/* Week data row */}
                  <tr style={{ borderBottom: '1px solid var(--ifm-color-emphasis-200)' }}>
                  <td style={{
                    padding: '0.75rem',
                    fontWeight: 'bold',
                    verticalAlign: 'top',
                    backgroundColor: 'var(--ifm-color-emphasis-50)'
                  }}>
                    {weekNum}
                  </td>

                  {daysOfWeek.map(day => {
                    const dateStr = datesByDay.get(day);

                    // No date for this day in this week - show gray cell
                    if (!dateStr) {
                      return (
                        <td key={day} style={{
                          padding: '0.75rem',
                          backgroundColor: 'var(--ifm-color-emphasis-100)',
                          verticalAlign: 'top',
                          minHeight: '60px'
                        }}>
                          <div style={{
                            fontSize: '0.75rem',
                            color: 'var(--ifm-color-emphasis-500)',
                            fontStyle: 'italic',
                            textAlign: 'center'
                          }}>
                            No class
                          </div>
                        </td>
                      );
                    }

                    const entriesForDate = entryMap.get(dateStr);
                    const hasClassEntries = entriesForDate && entriesForDate.length > 0;
                    
                    // Check if there are assignments for this date (release or due)
                    const cellAssignments = assignmentsByWeek.has(weekNum) 
                      ? assignmentsByWeek.get(weekNum)!.filter(assignment => {
                          if (!assignment.assignedDate || !assignment.dueDate) return false;
                          const assignedDate = parseISO(assignment.assignedDate);
                          const dueDate = parseISO(assignment.dueDate);
                          return format(assignedDate, 'yyyy-MM-dd') === dateStr ||
                            format(dueDate, 'yyyy-MM-dd') === dateStr;
                        })
                      : [];
                    
                    // Date exists but no class entry - show "No class" but still render assignments
                    if (!hasClassEntries) {
                      const date = parseISO(dateStr);
                      const formattedDate = format(date, 'MMM d');
                      
                      return (
                        <td key={day} style={{
                          padding: '0.75rem',
                          backgroundColor: 'var(--ifm-color-emphasis-100)',
                          verticalAlign: 'top'
                        }}>
                          <div style={{ fontSize: '0.85rem', color: 'var(--ifm-color-emphasis-700)', marginBottom: '0.25rem' }}>
                            {formattedDate}
                          </div>
                          <div style={{
                            fontSize: '0.75rem',
                            color: 'var(--ifm-color-emphasis-500)',
                            fontStyle: 'italic',
                            textAlign: 'center',
                            marginBottom: cellAssignments.length > 0 ? '0.5rem' : 0
                          }}>
                            No class
                          </div>
                          {/* Show assignments even on non-class days */}
                          {cellAssignments.length > 0 && (
                            <Box
                              borderRadius="md"
                              p="2"
                              bg="bg.emphasized"
                            >
                              {cellAssignments.map((assignment, idx) => {
                                if (!assignment.assignedDate || !assignment.dueDate) return null;
                                const assignedDate = parseISO(assignment.assignedDate);
                                const dueDate = parseISO(assignment.dueDate);
                                const isReleased = format(assignedDate, 'yyyy-MM-dd') === dateStr;
                                const isDue = format(dueDate, 'yyyy-MM-dd') === dateStr;
                                return (
                                  <div key={assignment.id} style={{ marginBottom: idx < cellAssignments.length - 1 ? '0.5rem' : '0' }}>
                                    <div style={{ fontSize: '0.8rem' }}>
                                      {isReleased && (
                                        <div style={{ marginBottom: isDue ? '0.25rem' : '0' }}>
                                          <strong>RELEASED:</strong>{' '}
                                          {assignment.url ? (
                                            <Link to={getAssignmentUrl ? getAssignmentUrl(assignment.url) || assignment.url : assignment.url}>{assignment.title}</Link>
                                          ) : (
                                            assignment.title
                                          )}
                                        </div>
                                      )}
                                      {isDue && (
                                        <div>
                                          <strong>DUE:</strong>{' '}
                                          {assignment.url ? (
                                            <Link to={getAssignmentUrl ? getAssignmentUrl(assignment.url) || assignment.url : assignment.url}>{assignment.title}</Link>
                                          ) : (
                                            assignment.title
                                          )}
                                          {assignment.dueTime && (
                                            <span style={{ fontSize: '0.7rem', color: 'var(--ifm-color-emphasis-600)' }}>
                                              {' '}at {assignment.dueTime}
                                            </span>
                                          )}
                                        </div>
                                      )}
                                    </div>
                                  </div>
                                );
                              })}
                            </Box>
                          )}
                        </td>
                      );
                    }

                    const date = parseISO(dateStr);
                    const formattedDate = format(date, 'MMM d');

                    // Check if this is a holiday
                    const isHolidayCell = entriesForDate.some(e => !!e.holiday);
                    const holidayName = entriesForDate.find(e => e.holiday)?.holiday?.name || '';

                    // Display topics if available, otherwise show lectureId
                    const lectureEntry = entriesForDate.find(e => e.lecture);
                    const labEntriesForDate = entriesForDate.filter(e => e.meeting?.type === 'lab');
                    const labEntry = entriesForDate.find(e => e.lab);

                    const topic = lectureEntry?.lecture?.title
                      || (lectureEntry?.lecture?.topics && lectureEntry.lecture.topics.length > 0 ? lectureEntry.lecture.topics[0] : '')
                      || lectureEntry?.lecture?.lectureId
                      || '';
                    const notes = lectureEntry?.notes || lectureEntry?.meeting.notes || '';

                    const cellStyle: React.CSSProperties = {
                      padding: '0.75rem',
                      verticalAlign: 'top',
                      backgroundColor: isHolidayCell ? '#fff3cd' : undefined,
                      borderLeft: isHolidayCell ? '3px solid #ffc107' : undefined,
                    };

                    return (
                      <td key={day} style={cellStyle}>
                        <div style={{ fontSize: '0.85rem', color: 'var(--ifm-color-emphasis-700)', marginBottom: '0.25rem' }}>
                          {formattedDate}
                        </div>
                        {isHolidayCell ? (
                          <>
                            <div style={{
                              fontWeight: 'bold',
                              color: '#856404',
                              marginBottom: '0.25rem'
                            }}>
                              {holidayName}
                            </div>
                            <div style={{
                              fontSize: '0.8rem',
                              color: '#856404',
                              fontStyle: 'italic'
                            }}>
                              No Class
                            </div>
                          </>
                        ) : lectureEntry?.lecture?.lectureId ? (
                          <div style={{ marginBottom: '0.25rem' }}>
                            <Link to={`/lecture-notes/${lectureEntry.lecture.lectureId}`}>
                              {topic}
                            </Link>
                          </div>
                        ) : (
                          <div style={{ marginBottom: '0.25rem' }}>
                            {topic}
                          </div>
                        )}
                        {notes && !isHolidayCell && (
                          <div style={{
                            fontSize: '0.8rem',
                            color: 'var(--ifm-color-emphasis-600)',
                            fontStyle: 'italic'
                          }}>
                            {notes}
                          </div>
                        )}

                        {/* Show lab if scheduled on this date */}
                        {labEntriesForDate.length > 0 && !isHolidayCell && (
                          <Box mt="2">
                            {labEntriesForDate.map((labE, idx) => {
                              const label = labE.lab?.title || 'Lab session';
                              const url = labE.lab?.url;
                              return (
                                <div key={idx} style={{ marginBottom: idx < labEntriesForDate.length - 1 ? '0.5rem' : 0 }}>
                                  {url ? (
                                    <Link to={url}>
                                      <div>{label}</div>
                                    </Link>
                                  ) : (
                                    <div>{label}</div>
                                  )}
                                  {labE.lab?.points && (
                                    <div style={{ fontSize: '0.75rem', color: 'var(--ifm-color-emphasis-700)', marginTop: '0.25rem' }}>
                                      {labE.lab.points} points
                                    </div>
                                  )}
                                  {!labE.lab && (
                                    <div style={{ fontSize: '0.7rem', color: 'var(--ifm-color-emphasis-600)', fontStyle: 'italic' }}>
                                      Lab mapped by meeting day/time
                                    </div>
                                  )}
                                </div>
                              );
                            })}
                          </Box>
                        )}

                        {/* Show assignments in relevant date cells */}
                        {cellAssignments.length > 0 && (
                          <Box
                            borderRadius="md"
                            p="2"
                            mt="2"
                            bg="bg.emphasized"
                          >
                            {cellAssignments.map((assignment, idx) => {
                              // These should always exist due to filtering, but check anyway
                              if (!assignment.assignedDate || !assignment.dueDate) return null;

                              const assignedDate = parseISO(assignment.assignedDate);
                              const dueDate = parseISO(assignment.dueDate);

                              const isReleased = format(assignedDate, 'yyyy-MM-dd') === dateStr;
                              const isDue = format(dueDate, 'yyyy-MM-dd') === dateStr;

                              return (
                                <div key={assignment.id} style={{ marginBottom: idx < cellAssignments.length - 1 ? '0.5rem' : '0' }}>
                                  <div style={{ fontSize: '0.8rem' }}>
                                    {isReleased && (
                                      <div style={{ marginBottom: isDue ? '0.25rem' : '0' }}>
                                        <strong>RELEASED:</strong>{' '}
                                        {assignment.url ? (
                                          <Link to={getAssignmentUrl ? getAssignmentUrl(assignment.url) || assignment.url : assignment.url}>{assignment.title}</Link>
                                        ) : (
                                          assignment.title
                                        )}
                                      </div>
                                    )}
                                    {isDue && (
                                      <div>
                                        <strong>DUE:</strong>{' '}
                                        {assignment.url ? (
                                          <Link to={getAssignmentUrl ? getAssignmentUrl(assignment.url) || assignment.url : assignment.url}>{assignment.title}</Link>
                                        ) : (
                                          assignment.title
                                        )}
                                        {assignment.dueTime && (
                                          <span style={{ fontSize: '0.7rem', color: 'var(--ifm-color-emphasis-600)' }}>
                                            {' '}at {assignment.dueTime}
                                          </span>
                                        )}
                                      </div>
                                    )}
                                  </div>
                                </div>
                              );
                            })}
                          </Box>
                        )}
                      </td>
                    );
                  })}
                </tr>
                </React.Fragment>
              );
            })}
          </tbody>
        </table>
      </div>
    </div>
  );
}

export default function SchedulePage({ scheduleData }: Props) {
  const { config, scheduleBySection } = scheduleData;
  const baseUrl = useBaseUrl('/');

  // Helper function to get assignment URL with base URL
  const getAssignmentUrl = (url: string | undefined): string | undefined => {
    if (!url) return undefined;
    // If URL already starts with baseUrl, return as is
    if (url.startsWith(baseUrl)) return url;
    // If URL starts with '/', prepend baseUrl (removing trailing slash from baseUrl)
    if (url.startsWith('/')) {
      const base = baseUrl.endsWith('/') ? baseUrl.slice(0, -1) : baseUrl;
      return `${base}${url}`;
    }
    // Otherwise, prepend baseUrl
    return `${baseUrl}${url}`;
  };

  const [selectedLectureId, setSelectedLectureId] = useState<string>(() => 
    config.sections.find(s => s.timeZone === 'America/New_York')?.id || config.sections[0]?.id || ''
  );
  const [selectedLabId, setSelectedLabId] = useState<string>(() => 
    config.labSections?.find(s => s.timeZone === 'America/New_York')?.id || config.labSections?.[0]?.id || ''
  );

  // Hydrate selections from localStorage on client
  useEffect(() => {
    if (typeof window === 'undefined') return;
    const savedLecture = window.localStorage.getItem('cs3100.schedule.lectureSection');
    const savedLab = window.localStorage.getItem('cs3100.schedule.labSection');
    if (savedLecture && config.sections.some(s => s.id === savedLecture)) {
      setSelectedLectureId(savedLecture);
    }
    if (savedLab && config.labSections?.some(s => s.id === savedLab)) {
      setSelectedLabId(savedLab);
    }
  }, [config.sections, config.labSections]);

  // Persist selections
  useEffect(() => {
    if (typeof window === 'undefined') return;
    if (selectedLectureId) {
      window.localStorage.setItem('cs3100.schedule.lectureSection', selectedLectureId);
    }
    if (selectedLabId) {
      window.localStorage.setItem('cs3100.schedule.labSection', selectedLabId);
    }
  }, [selectedLectureId, selectedLabId]);

  const lectureSection: CourseSection | undefined = useMemo(
    () => config.sections.find(s => s.id === selectedLectureId) || config.sections[0],
    [config.sections, selectedLectureId]
  );

  const labSection: LabSection | undefined = useMemo(
    () => config.labSections?.find(s => s.id === selectedLabId) || config.labSections?.[0],
    [config.labSections, selectedLabId]
  );

  const lectureEntries = lectureSection ? scheduleBySection[lectureSection.id] || [] : [];
  const labEntries = useMemo(() => {
    if (!labSection) {
      return [];
    }

    const bySection = scheduleData.labScheduleBySection?.[labSection.id] || [];
    if (bySection.length > 0) {
      return bySection;
    }

    const fallback = scheduleData.allEntries.filter((e) => e.sectionId === labSection.id);
    return fallback;
  }, [labSection, scheduleData.labScheduleBySection, scheduleData.allEntries]);

  // Build meeting day arrays
  const lectureDays = useMemo(() => {
    if (!lectureSection) return [];
    const days = new Set<string>();
    lectureSection.meetings.forEach(m => {
      if (m.type === 'lab') return;
      m.days.forEach(d => days.add(d));
    });
    return Array.from(days);
  }, [lectureSection]);

  const labDays = useMemo(() => {
    if (!labSection) return [];
    const days = new Set<string>();
    labSection.meetings.forEach(m => {
      m.days.forEach(d => days.add(d));
    });
    return Array.from(days);
  }, [labSection]);

  // Combine lecture + lab entries for unified display
  const combinedEntries = useMemo(() => {
    const all = [...lectureEntries, ...labEntries];
    const sorted = all.sort((a, b) => a.date.localeCompare(b.date));
    return sorted;
  }, [lectureEntries, labEntries, lectureSection?.id, labSection?.id]);

  const combinedSectionName = useMemo(() => {
    const lecturePart = lectureSection ? `${lectureSection.name}` : 'Lecture';
    const labPart = labSection ? `${labSection.name}` : 'Lab';
    return `${lecturePart} + ${labPart}`;
  }, [lectureSection, labSection]);

  const formatDays = (days: string[]) => days.map(d => d.slice(0, 3)).join('/');
  const inferCampus = (location?: string, timeZone?: string) => {
    if (location) {
      if (/oakland/i.test(location)) return 'Oakland';
      if (/boston/i.test(location)) return 'Boston';
    }
    if (timeZone === 'America/Los_Angeles') return 'Oakland';
    if (timeZone === 'America/New_York') return 'Boston';
    return 'Campus';
  };

  const lectureLabel = (section: CourseSection) => {
    const lectureMeeting = section.meetings.find(m => m.type !== 'lab') || section.meetings[0];
    const days = lectureMeeting ? formatDays(lectureMeeting.days) : '';
    const startEnd = lectureMeeting ? `${lectureMeeting.startTime}-${lectureMeeting.endTime}` : '';
    const campus = inferCampus(lectureMeeting?.location, section.timeZone);
    const instructor = section.instructors?.[0] || 'Staff';
    return `(${instructor} ${days} ${startEnd} ${campus})`;
  };

  const labLabel = (lab: LabSection) => {
    const meeting = lab.meetings[0];
    const days = meeting ? formatDays(meeting.days) : '';
    const startEnd = meeting ? `${meeting.startTime}-${meeting.endTime}` : '';
    const campus = inferCampus(meeting?.location, lab.timeZone);
    return `(${days} ${startEnd} ${campus})`;
  };

  return (
    <Layout
      title={`Schedule - ${config.courseCode}`}
      description={`Course schedule for ${config.courseCode}: ${config.courseTitle}`}
    >
      <div style={{ padding: '2rem', maxWidth: '1200px', margin: '0 auto' }}>
        <header style={{ marginBottom: '2rem' }}>
          <h1>{config.courseCode}: {config.courseTitle}</h1>
          <p style={{ fontSize: '1.2rem', color: 'var(--ifm-color-emphasis-700)' }}>
            {config.semester} | {config.academicYear}
          </p>
          <p>
            <strong>Duration:</strong> {format(parseISO(config.startDate), 'MMM d, yyyy')} - {format(parseISO(config.endDate), 'MMM d, yyyy')}
          </p>
        </header>

        {/* Section selector */}
        <div style={{ marginBottom: '1.5rem', display: 'flex', gap: '1rem', flexWrap: 'wrap' }}>
          <div>
            <label htmlFor="lecture-section-select" style={{ display: 'block', fontWeight: 'bold' }}>Lecture section</label>
            <select
              id="lecture-section-select"
              value={selectedLectureId}
              onChange={(e) => setSelectedLectureId(e.target.value)}
              style={{ padding: '0.5rem', minWidth: '220px' }}
            >
              {config.sections.map((section) => (
                <option key={section.id} value={section.id}>
                  {section.name} {section.crn ? `(${section.crn})` : ''} {lectureLabel(section)}
                </option>
              ))}
            </select>
          </div>

          {config.labSections && config.labSections.length > 0 && (
            <div>
              <label htmlFor="lab-section-select" style={{ display: 'block', fontWeight: 'bold' }}>Lab section</label>
              <select
                id="lab-section-select"
                value={selectedLabId}
                onChange={(e) => setSelectedLabId(e.target.value)}
                style={{ padding: '0.5rem', minWidth: '220px' }}
              >
                {config.labSections.map((lab) => (
                  <option key={lab.id} value={lab.id}>
                    {lab.name} {lab.crn ? `(${lab.crn})` : ''} {labLabel(lab)}
                  </option>
                ))}
              </select>
            </div>
          )}
        </div>

        {/* Combined schedule */}
        <div>
          <h2>Course Schedule</h2>
          <Box>
            Loosely, the course is organized as follows:
            <ul>
              <li>Module 1 (weeks 1 - 4): Design in the small — Java fundamentals, design principles, changeability</li>
              <li>Module 2 (weeks 5 - 10): Design in the large — testing, teams, architecture, distributed systems</li>
              <li>Module 3 (weeks 11 - 15): Design for users — UCD, accessibility, GUIs, concurrency</li>
            </ul>
            Modules 1 and 2 are each followed by an exam, and Module 3 is followed by a cumulative final exam.
          </Box>
          <ScheduleTable
            entries={combinedEntries}
            sectionName={combinedSectionName}
            lectureDays={lectureDays}
            labDays={labDays}
            assignments={config.assignments || []}
            scheduleNotes={config.scheduleNotes}
            lectureSectionId={selectedLectureId}
            labSectionId={selectedLabId}
            getAssignmentUrl={getAssignmentUrl}
          />
        </div>

        {/* Assignments (if any) */}
        {config.assignments && config.assignments.length > 0 && (
          <div style={{ marginTop: '3rem' }}>
            <h2>Assignments</h2>
            <table style={{ width: '100%', borderCollapse: 'collapse' }}>
              <thead>
                <tr style={{ borderBottom: '2px solid var(--ifm-color-emphasis-300)' }}>
                  <th style={{ padding: '0.75rem', textAlign: 'left' }}>Assignment</th>
                  <th style={{ padding: '0.75rem', textAlign: 'left' }}>Type</th>
                  <th style={{ padding: '0.75rem', textAlign: 'left' }}>Assigned</th>
                  <th style={{ padding: '0.75rem', textAlign: 'left' }}>Due</th>
                  <th style={{ padding: '0.75rem', textAlign: 'left' }}>Points</th>
                </tr>
              </thead>
              <tbody>
                {config.assignments.map((assignment) => (
                  <tr key={assignment.id} style={{ borderBottom: '1px solid var(--ifm-color-emphasis-200)' }}>
                    <td style={{ padding: '0.75rem' }}>
                      {assignment.url ? (
                        <Link to={getAssignmentUrl(assignment.url) || assignment.url}>{assignment.title}</Link>
                      ) : (
                        assignment.title
                      )}
                    </td>
                    <td style={{ padding: '0.75rem' }}>{assignment.type}</td>
                    <td style={{ padding: '0.75rem' }}>
                      {assignment.assignedDate ? format(parseISO(assignment.assignedDate), 'MMM d, yyyy') : 'TBD'}
                    </td>
                    <td style={{ padding: '0.75rem' }}>
                      {assignment.dueDate ? format(parseISO(assignment.dueDate), 'MMM d, yyyy') : 'TBD'}
                      {assignment.dueTime && ` ${assignment.dueTime}`}
                    </td>
                    <td style={{ padding: '0.75rem' }}>{assignment.points || '-'}</td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
        )}

        {/* Office Hours */}
        {config.metadata?.officeHours && config.metadata.officeHours.length > 0 && (
          <div style={{ marginTop: '3rem' }}>
            <h2>Office Hours</h2>
            {config.metadata.officeHours.map((oh, idx) => (
              <div key={idx} style={{ marginBottom: '1rem' }}>
                <p><strong>{oh.instructor}:</strong> {oh.schedule}</p>
                <p>Location: {oh.location}</p>
                {oh.bookingUrl && (
                  <p><a href={oh.bookingUrl} target="_blank" rel="noopener noreferrer">Book appointment</a></p>
                )}
              </div>
            ))}
          </div>
        )}
      </div>
    </Layout>
  );
}

